### ISSUE TITLE
Can't run on MacOSX

### ISSUE THREAD

**Issue by nguyentamdotme** [ngxson/inlets-heroku#1]
I use MacOSx and when I run file **run-linux.sh** in _Client_ folder I get error: **_line 8: ../bin/inlets: cannot execute binary file_**

**Comment by sahilmob** [comment]
@nguyentamdotme  here is what you have to do:

1- Install inlets CLI via brew 
```
brew install inlets
```


2-Start the tunnel client:
```
export REMOTE="https://example.herokuapp.com"
export TOKEN="CLIENT-TOKEN-HERE"
export UPSTREAM="http://127.0.0.1:3000 "

inlets client \
 --remote=$REMOTE \
 --upstream=$UPSTREAM \
 --token $TOKEN
```

[Reference](https://github.com/inlets/inlets)

**Comment by ngxson** [comment]
Sorry I haven't received notification for this issue. I don't have a mac device to test it, but many thanks to @sahilmob 
Support for MacOS will be added in the next version

**Comment by nguyentamdotme** [comment]
> @nguyentamdotme here is what you have to do:
> 
> 1- Install inlets CLI via brew
> 
> ```
> brew install inlets
> ```
> 
> 2-Start the tunnel client:
> 
> ```
> export REMOTE="https://example.herokuapp.com"
> export TOKEN="CLIENT-TOKEN-HERE"
> export UPSTREAM="http://127.0.0.1:3000 "
> 
> inlets client \
>  --remote=$REMOTE \
>  --upstream=$UPSTREAM \
>  --token $TOKEN
> ```
> 
> [Reference](https://github.com/inlets/inlets)

It working for me. Thank you so much, @sahilmob !

**Comment by ngxson** [comment]
Added script for MacOS
